
--// The Strongest BattleGrounds -- 10449761463
if game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/tsb.luau"))()
--// USL Match Pitch -- 82612352646016
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/USL.luau"))()
--// TPS Street Soccer -- 335760407
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://github.com/RyzeDevelopment/Ryze-Vault/edit/main/TPS.luau"))()
--// Rivals -- 17625359962
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://github.com/RyzeDevelopment/Ryze-Vault/edit/main/RIVALS.luau"))()
--// Legends Of Speed -- 3101667897
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/LOS.luau"))()
--// TOH -- 1962086868
elseif game.PlaceId == 118614517739521 then
    loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/TOH.luau"))()
--// Murder Mystery 2 -- 142823291
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/mm2.luau"))()
--// Bladeball
elseif game.PlaceId == 118614517739521 then
--// Blind Shoot -- 118614517739521
elseif game.PlaceId == 118614517739521 then
loadstring(game:httpget("https://raw.githubusercontent.com/RyzeDevelopment/Ryze-Vault/refs/heads/main/blindshot.luau"))()
else then
    print("dady")
end
