
--// The Strongest BattleGrounds -- 10449761463 -- emresozer -- google
if game.PlaceId == 10449761463 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/b12343c7769151f01da6f11de350a3c5b84bc90098cb41cb584d62349b3e0046/download"))()
--// USL Match Pitch -- 82612352646016 -- emresozer -- google
elseif game.PlaceId == 82612352646016 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/bb6a3a0d5c3c0feb082817a017adf6fec7afd35af56e447585563935e0828d36/download"))()
--// TPS Street Soccer -- 335760407 -- emresozer -- google
elseif game.PlaceId == 335760407 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/f1aa509ac3aee03342c0ea8e5410c985b0c1b85f62400e1545e4da4049a7f03a/download"))()
--// Rivals -- 17625359962 -- zerai -- zerai google
elseif game.PlaceId == 118614517739521 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/d7bd25796b94519799d06d555e15172c2a4ded2400d345c4be0782883957f6fc/download"))()
--// Legends Of Speed -- 3101667897 -- emresozer -- google
elseif game.PlaceId == 3101667897 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/6eb587751b773cfb7d48caa462af8d67f026ea4ff24f224711b92d0c57247d7b/download"))()
--// TOH -- 1962086868 -- zerai -- zerai google
elseif game.PlaceId == 1962086868 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/09e9b785a18c32f5de71c47d5452d3c3245f6c55f52d012219221e2e92fab6c0/download"))()
--// Murder Mystery 2 -- 142823291 -- zerai - zerai google
elseif game.PlaceId == 142823291 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/8c11f9f25063c896a4c9366f2a9d2928664f864152b55a88b326a44eac9c3999/download"))()
--// Bladeball -- 13772394625 -- zerai - zerai google
elseif game.PlaceId == 13772394625 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/cbed88e055d2a22e6dd598569795ad66f1238935bb0dc0398ecefa4df04eaf4e/download"))()
--// Blind Shoot -- 118614517739521 -- emresozer -- google
elseif game.PlaceId == 118614517739521 then
loadstring(game:HttpGet("https://api.junkie-development.de/api/v1/luascripts/public/e2c7c5181eadeb1c13964126b82a73f2a5d9745cbbc4a60bb156f0bb0be2e327/download"))()
--// Chop Your Tree -- 123557829667240 -- zerai -- google
elseif game.PlaceId == 123557829667240 then
loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/ea891ca4d70c89ef201978a9bd84424176f55a70225717d3e865cec54c2c1f37/download"))()
else
    print("dady")
end
